# [[plugins]]
# repo = 'Shougo/dein.vim'

# [[plugins]]
# repo = 'Shougo/vimshell'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]] # カーソル位置のコンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]] # カーソル位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'wakatime/vim-wakatime'

# https://qiita.com/kawaz/items/ee725f6214f91337b42b
# [[plugins]] # カラースキーマ
# repo = 'w0ng/vim-hybrid'
# hook_add = '''
#  set background=dark
#  " colorscheme 設定は source 後に行う必要があるので VimEnter で行う。
#  " 但し Colorscheme イベントの発生が抑制されないよう nented を付ける。
#  au MyAutoCmd VimEnter * nested colorscheme hybrid
#'''

# [[plugins]]
# repo = 'LeafCage/yankround.vim'
# hook_add = '''
# nmap p <Plug>(yankround-p)
# xmap p <Plug>(yankround-p)
# nmap P <Plug>(yankround-P)
# nmap gp <Plug>(yankround-gp)
# xmap gp <Plug>(yankround-gp)
# nmap gP <Plug>(yankround-gP)
# nmap <C-p> <Plug>(yankround-prev)
# nmap <C-n> <Plug>(yankround-next)
# '''

