tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'homebrew/brewdler'
tap 'homebrew/core'
tap 'josegonzalez/php'
cask 'java'
brew 'autoconf'
brew 'coreutils'
brew 'curl'
brew 'gdbm'
brew 'git'
brew 'openssl'
brew 'libevent'
brew 'mas'
brew 'nvm'
brew 'pcre'
brew 'pkg-config'
brew 'pwgen'
brew 'readline'
brew 'pyenv'
brew 'ruby-build'
brew 'rbenv'
brew 'reattach-to-user-namespace'
brew 'sbt'
brew 'scala'
brew 'tmux'
brew 'wget'
brew 'zsh'
brew 'zsh-completions'
cask '1password'
cask 'alfred2'
cask 'atom'
cask 'google-chrome'
cask 'google-cloud-sdk'
cask 'google-drive'
cask 'iterm2'
cask 'macvim-kaoriya'
cask 'screenhero'
cask 'slack'
cask 'tunnelblick'
cask 'vagrant'
cask 'virtualbox'
mas 'Kindle', id: 405399194
mas 'CotEditor', id: 1024640650
mas 'GarageBand', id: 682658836
mas 'iMovie', id: 408981434
mas 'Pages', id: 409201541
mas 'Keynote', id: 409183694
mas 'TweetDeck', id: 485812721
mas 'LINE', id: 539883307
mas 'Numbers', id: 409203825
