[settings]
github.github_attestations = false
ruby.compile = false

[tools]
java = "temurin-26.0.0"
node = "25"
python = "3.14.3"
ruby = "4.0"
claude = "2.1.90"
codex = "0.118.0"
"npm:takt" = "0.33.2"
"npm:happy-coder" = "0.13.0"
"npm:npm-check-updates" = "20.0.0"
"npm:@github/copilot" = "1.0.17"
