[settings]
github.github_attestations = false
ruby.compile = false

[tools]
java = "temurin-26.0.0"
node = "25"
python = "3.14.4"
ruby = "4.0"
claude = "2.1.107"
codex = "0.120.0"
"npm:takt" = "0.35.4"
"npm:happy-coder" = "0.13.1"
"npm:npm-check-updates" = "20.0.2"
"npm:@github/copilot" = "1.0.26"
