[settings]
github.github_attestations = false
ruby.compile = false

[tools]
java = "temurin-26.0.0"
node = "25"
python = "3.14.4"
ruby = "4.0"
claude = "2.1.118"
codex = "0.123.0"
"npm:takt" = "0.37.0"
"npm:happy-coder" = "0.13.1"
"npm:npm-check-updates" = "21.0.3"
"npm:@github/copilot" = "1.0.35"
